name: Broken page
description: A *specific* page or blog post has a problem. If you want to report a problem with the website in general, please use the "Bug" template instead.
title: 'Broken page: [Page title]'
labels: broken-page
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: url
    attributes:
      label: "Page URL:"
      description: URL of the page that is broken
      placeholder: ex. https://lea.verou.me/blog/2020/12/writable-getters/
    validations:
      required: true
  - type: input
    id: oldurl
    attributes:
      label: "Old URL:"
      description: |
        URL of the page on the previous website.
        If you followed a "Report broken page" link from the website, this should be already filled in for you.
        If it isn’t, this
  - type: dropdown
    id: is_regression
    attributes:
      label: Did this page work in the previous website?
      description: |
        If you followed a "Report broken page" link from the website, you can find the old URL above, if one existed.
        If not, you can usually find the same page on the old website by using `lea0.verou.me` instead of `lea.verou.me` and replacing `/blog/` with `/`.
      options:
        - "Yes"
        - "No"
        - "N/A"
    validations:
      required: true
  - type: dropdown
    id: issues
    attributes:
      label: What issues do you see?
      description: Please select all that apply
      multiple: true
      options:
        - Broken image(s)
        - Broken embed(s)
        - Figure caption not styled as a caption
        - Broken styles
        - Broken URLs
        - Broken syntax highlighting
        - Accessibility issue
        - Other
  - type: textarea
    id: details
    attributes:
      label: Description of issues
      description: Please provide more details
    validations:
      required: true
