# The directory where our serverless functions are located.
[functions]
	directory = "netlify/functions"
	node_bundler = "esbuild"
[[headers]]
	# What the headers are for
  for = "/*"
	# Headers to set
	[headers.values]
	# CORS
	X-Content-Type-Options = "nosniff"
	Access-Control-Allow-Origin = "*"
	# Client Hints
	Accept-CH = "Sec-CH-Width"
	Permissions-Policy = 'ch-width=(self "https://images.cloudfour.com")'
