# The directory where our serverless functions are located.
[functions]
	directory = "netlify/functions"
	node_bundler = "esbuild"
[[headers]]
  for = "/*"
    [headers.values]
		X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "*"
