name: Broken page
description: A *specific* page or blog post has a problem. If you want to report a problem with the website in general, please use the "Bug" template instead.
title: 'Broken page: [Page title]'
labels: broken-page
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: url
    attributes:
      label: "Page URL:"
      description: URL of the page that is broken
      placeholder: ex. https://publishing-project.rivendellweb.net/my-markdown-cheatsheet/
    validations:
      required: true
  - type: dropdown
    id: issues
    attributes:
      label: What issues do you see?
      description: Please select all that apply
      multiple: true
      options:
        - Broken image(s)
        - Broken embed(s)
        - Figure caption not styled as a caption
        - Broken styles
        - Broken URLs
        - Broken syntax highlighting
        - Accessibility issue
        - Other
  - type: textarea
    id: details
    attributes:
      label: Description of issues
      description: Please provide more details
    validations:
      required: true


